### ISSUE TITLE
Check bibliographies in all ITU documents

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#105]
As requested in https://github.com/metanorma/mn-samples-itu/issues/79#issuecomment-635326000

Task is to check the bibliographies of all the documents from this repository.

**Comment by manuelfuenmayor** [comment]
After some checking, I found that the references are not rendering properly.
For example,

````
[bibliography]
[[References]]
== References

* [[[ITU-T_A.5,ITU-T A.5]]] Recommendation ITU-T A.5 (2016), _Generic procedures for including references to documents of other organizations in ITU-T Recommendations._

* [[[ITU-T_A.23,ITU-T A.23]]] Recommendation ITU-T A.23, Annex A (2014), _Guide for ITU-T and ISO/IEC JTC 1 cooperation._
````

*Output:*

![Capture](https://user-images.githubusercontent.com/33627611/83356189-4d5f3980-a332-11ea-9366-01f1d64de153.PNG)


Ticket created in: https://github.com/metanorma/metanorma-itu/issues/212

**Comment by manuelfuenmayor** [comment]
@anermina , I'm getting issues related with fetching. When I compile, it says:
````
[relaton-itu] ("ITU-T G.192") fetching...
C:/tools/ruby25/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': 
Failed to open TCP connection to :80 
(No connection could be made because the target machine actively refused it. - connect(2) 
for nil port 80) (Errno::ECONNREFUSED)
````
Could you please confirm the fetching function is working properly?
For instance, this error occurred to me with [G.191.adoc](https://raw.githubusercontent.com/metanorma/mn-samples-itu/master/sources/G.191.adoc) (among others).

Thanks!

**Comment by manuelfuenmayor** [comment]
Oh, and apparently these changes have not been incorporated in the last release yet. So you'll have to update directly from metanorma-itu repository.

**Comment by opoudjis** [comment]
And just as well they haven't :( Really surprised, but OK, I'm prioritising.

**Comment by anermina** [comment]
> Could you please confirm the fetching function is working properly?
> For instance, this error occurred to me with [G.191.adoc](https://raw.githubusercontent.com/metanorma/mn-samples-itu/master/sources/G.191.adoc) (among others).

I'm not getting any bibliography-related issues when using metanorma-itu for G.191. Will check for other documents as well.

**Comment by manuelfuenmayor** [comment]
> > Could you please confirm the fetching function is working properly?
> > For instance, this error occurred to me with [G.191.adoc](https://raw.githubusercontent.com/metanorma/mn-samples-itu/master/sources/G.191.adoc) (among others).
> 
> I'm not getting any bibliography-related issues when using metanorma-itu for G.191. Will check for other documents as well.

It's ok @anermina. I can fetch properly now after executing the latest update. Thanks!

**Comment by manuelfuenmayor** [comment]
By the way, I also have found this new issue: 

![Capture4](https://user-images.githubusercontent.com/33627611/83778839-39307a80-a659-11ea-8834-857fde101ea0.PNG)
(The identifiers are getting separated in lines)
I have informed Nick already in https://github.com/metanorma/metanorma-itu/issues/212#issuecomment-638941609.

**Comment by manuelfuenmayor** [comment]
All good now! Closing.
