### ISSUE TITLE
Install Times New Roman fonts for ITU

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#112]
ITU uses Times New Roman fonts, but they are not available on the PDF layouts in the output.

Please use https://github.com/fontist/fontist to install the necessary fonts.

**Comment by ronaldtse** [comment]
Ping @CAMOBAP . Thanks!

**Comment by ronaldtse** [comment]
This can be closed when `metanorma setup` is used here.

**Comment by CAMOBAP** [comment]
@ronaldtse yep, each flow except windows have it, so I think we can close this
