### ISSUE TITLE
Capital letters in table headings

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-itu#117]
All words in table headings are automatically written with capital letter, which isn't correct in some cases. Following example with metric units illustrates the issue.

![image](https://user-images.githubusercontent.com/55683568/87256035-e59f2100-c48f-11ea-8fbd-caae37472079.png)

**Comment by opoudjis** [comment]
@anermina I cannot find this example in the mn-samples-itu contents: can you give me an example?

**Comment by anermina** [comment]
@opoudjis sure, example is attached.
[table_test.zip](https://github.com/metanorma/mn-samples-itu/files/5018068/table_test.zip)

**Comment by opoudjis** [comment]
I've mistakenly used `titlecase`, the spec is clear that only the first word of the heading should be capitalised, and that is `capitalize`
