### ISSUE TITLE
Create sample: H.Imp248 : Implementors' Guide for the H.248 Sub-series of Recommendations ("Media Gateway Control Protocol")

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#126]
https://www.itu.int/rec/T-REC-H.Imp248-201710-I

NOTE: This is an implementers guide to a "series".

**Comment by ronaldtse** [comment]
Ping @anermina on progress, thanks.

**Comment by anermina** [comment]
Converted in #142.
After reviewing generation of strikethrough and underlined text, I will open a new ticket to address the noticed issue, if needed.
Closing this one.
