### ISSUE TITLE
Error: multiple instances of same ID

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-samples-itu#138]
https://github.com/metanorma/mn-samples-itu/runs/2040568410?check_suite_focus=true#step:5:39214

```
...
Anchors: (XML Line 000001): Anchor tbl_known-endian has already been used at line 567
Error: multiple instances of same ID
```

@ronaldtse could you please assign it to someone who familiar with it? If not, I can dig into it

Similar to https://github.com/metanorma/mn-samples-ietf/issues/43

**Comment by ronaldtse** [comment]
@metanorma/editors  can you have a look here? Seems that there’s an identical anchor used. Thanks!

**Comment by anermina** [comment]
Issue is fixed in https://github.com/metanorma/mn-samples-itu/pull/139. Closing.
