### ISSUE TITLE
PDFs failed to compile on Arch Linux

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#152]
As #150 is completed, it seems that PDFs failed to be generated on Arch Linux.
* https://github.com/metanorma/mn-samples-itu/actions/runs/3086698559

<img width="326" alt="Screen Shot 2022-09-20 at 9 39 02 AM" src="https://user-images.githubusercontent.com/11865/191148421-8488aca6-519a-4558-8f71-ea11565bf08d.png">

The corresponding build on the Metanorma Docker container (Ubuntu) works:
* https://github.com/metanorma/mn-samples-itu/actions/runs/3086698600

@Intelligent2013 could you please help check to see what's going on? The error messages do not tell much. (We should find a way to display those error messages!)

Thanks.

**Comment by Intelligent2013** [comment]
> We should find a way to display those error messages!

@ronaldtse We've had this issue in the past, https://github.com/metanorma/mn2pdf-ruby/issues/10 re-opened.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

Do you know what the issue with generating the PDFs is?

**Comment by Intelligent2013** [comment]
@ronaldtse in progress yet....

**Comment by Intelligent2013** [comment]
Strange error occurs `java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null`:
```
[root@1e182575b1a4 mn-samples-itu]# java -Xss5m -Xmx2048m -jar /root/.local/share/gem/ruby/3.0.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/root/mn-samples-itu/site/documents/G.191.presentation.xml" --xsl-file "/root/.local/share/gem/ruby/3.0.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/itu.recommendation.xsl" --pdf-file "/root/mn-samples-itu/site/documents/G.191.pdf" --param baseassetpath="/root/mn-samples-itu/sources" --syntax-highlight  --font-manifest "/tmp/fontist_locations20220920-2061-jpazuw.yml"
mn2pdf


Preparing...
Input: XML (/root/mn-samples-itu/site/documents/G.191.presentation.xml)
Input: XSL (/root/.local/share/gem/ruby/3.0.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/itu.recommendation.xsl)
Input: XSL parameters ({baseassetpath=/root/mn-samples-itu/sources})
Output: PDF (/root/mn-samples-itu/site/documents/G.191.pdf)

[INFO] Generation of XSL-FO with information about the table's widths ...
[INFO] Generation of Intermediate Format with information about the table's widths ...
Can't obtain tables widths information: {0}
[INFO] XSL-FO file preparation...
Transforming to PDF...
java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
        at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
        at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)
        at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)
        at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:352)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:309)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:309)
        at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
        at java.desktop/sun.font.PlatformFontInfo.createFontManager(PlatformFontInfo.java:37)
        at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:51)
        at java.desktop/java.awt.Font.<init>(Font.java:642)
```

I need time for investigation.

**Comment by ronaldtse** [comment]
Looks like it couldn't find fonts?

**Comment by Intelligent2013** [comment]
Looks like there is issue in the linux fonts sub-system (`fontconfig`).
I've tried:
- `fc-list`
  - `command not found`
- `yes | pacman -Sy fontconfig`
- `fc-list`
   - nothing in the output
- run `mn2pdf`
    - `java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null`
- `yes | pacman -Sy ttf-dejavu`
- `fc-list`
    - `/usr/share/fonts/TTF/DejaVuSerifCondensed.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed,Book
/usr/share/fonts/TTF/DejaVuSansCondensed.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed,Book
/usr/share/fonts/TTF/DejaVuSans-BoldOblique.ttf: DejaVu Sans:style=Bold Oblique
`
- run `mn2pdf`
   - PDF generated successfully.

(solution found here https://www.reddit.com/r/archlinux/comments/njh6fd/comment/gz8ar1c/)

Preliminary reason of the issue - if there isn't any system known font, then error `"sun.awt.FontConfiguration.head" is null` occurs.

**Comment by ronaldtse** [comment]
Does this mean that we have to install fontconfig and also one `ttf-*` file for it to work?

**Comment by ronaldtse** [comment]
In this case can we implement a check to detect whether:
1. Does fontconfig exists? If not mn2pdf will fail?
2. If fontconfig exists but there is no font, mn2pdf should still work because it downloads the default fonts?

**Comment by Intelligent2013** [comment]
I've tried simple Java console program from https://blog.adoptopenjdk.net/2021/01/prerequisites-for-font-support-in-adoptopenjdk/ :
```java
import java.awt.*;

public class FontTest {

    public static void main(String[] args) {
        String[] names = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();

        System.out.println("Found " + names.length + " fonts:");

        for (String name : names) {
            System.out.println(name);
        }
    }
}
```

On Archlinux:
- without `fontconfig` and `ttf-dejavu`:
`Exception in thread "main" java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null`
- with installed `fontconfig` and `ttf-dejavu`:
```
Found 12 fonts:
DejaVu Math TeX Gyre
DejaVu Sans
DejaVu Sans Condensed
DejaVu Sans Light
DejaVu Sans Mono
DejaVu Serif
DejaVu Serif Condensed
Dialog
DialogInput
Monospaced
SansSerif
Serif
```

So, `fontconfig` (Java uses it internally) and one font should be installed (`ttf-dejavu`).

**Comment by Intelligent2013** [comment]
> Does fontconfig exists? If not mn2pdf will fail?

I think we can add a check for fontconfig existing, if it doesn't exist, then mn2pdf will exit with error.

> If fontconfig exists but there is no font, mn2pdf should still work because it downloads the default fonts?

No, because mn2pdf doesn't register fonts in the OS. One font as minimum should be installed in the system.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! I've made #153 to address this.
