### ISSUE TITLE
ITU-WHO Focus Group on AI for Health deliverables

### ISSUE THREAD

**Issue by bquast** [metanorma/mn-samples-itu#155]
The ITU-WHO (World Health Organization) Focus Group on Artificial Intelligence for Health (FG-AI4H), which as been active since 2018 has started publishing its deliverables:

https://www.itu.int/pub/T-FG-AI4H

Perhaps the word versions can serve as a basis for AsciiDoc? I'm asking about epub (i.e. HTML) or other "upstream" encodings.

**Comment by ronaldtse** [comment]
@bquast thanks for the suggestion, we're happy to add this example:
* [T-FG-AI4H-2022-MSW-E.docx](https://github.com/metanorma/mn-samples-itu/files/9788676/T-FG-AI4H-2022-MSW-E.docx)
* [T-FG-AI4H-2022-PDF-E.pdf](https://github.com/metanorma/mn-samples-itu/files/9788680/T-FG-AI4H-2022-PDF-E.pdf)

This is only 2022, is this the appropriate copy to convert?

**Comment by ronaldtse** [comment]
@metanorma/editors can you please help add this document as an example? Thanks!

**Comment by bquast** [comment]
Dear @ronaldtse yes that is the only copy, it was just released (it was approved at the 15th meeting in Berlin, May-June 2022).

**Comment by ronaldtse** [comment]
Thanks @bquast , the document is now encoded in #156 . Closing.

**Comment by bquast** [comment]
@ronaldtse thank you very much! this is great
