### ISSUE TITLE
Difference between margins in example block (DOC output only)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#16]
In example block, there is a noticeable difference between paragraph margin and list block margin.

[me-issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3729454/me-issue-sample.zip)

![sample (metanorma-compiled)](https://user-images.githubusercontent.com/33627611/66835194-1536f200-ef2d-11e9-97c8-33432b81574b.JPG)

![sample (original doc)](https://user-images.githubusercontent.com/33627611/66835205-19fba600-ef2d-11e9-9088-1334418a63e2.JPG)

**Comment by opoudjis** [comment]
We've inherited too much indentation for examples from ISO, which is not warranted for ITU anyway, and examples + list indentation is not working.

**Comment by opoudjis** [comment]
Oops. No, that doesn't work, because of EXAMPLE caption.

**Comment by opoudjis** [comment]
Unindentended EXAMPLE caption. Will review other flavours.

**Comment by opoudjis** [comment]
Adjusting all indented examples to propagate indentation by indenting only div.example
