### ISSUE TITLE
Convert ITU-T A.8 and WTSA Resolution 1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#19]
* https://www.itu.int/rec/T-REC-A.8-200810-I/en
* https://www.itu.int/pub/T-RES-T.1-2016

@anermina do you have time to help convert both of these? I've added them to reference-docs. Thanks!

**Comment by anermina** [comment]
Document style for resolution is quite different than for recommendation. As I understood, :doctype: resolution is not completely implemented yet. Please correct me if I'm wrong. 
Should I report all the noticed differences as issues?

I also have one question regarding the clauses in A.8 recommendation, which also seem to be different than those in the documents I've been working on so far. 
In this recommendation, clauses are untitled, their numbering is in the same row as the rest of the text for that clause, and they shouldn't appear in the table of contents. Should these clauses be defined in .adoc as the rest of them, or they should only be marked-up (boldfaced) to indicate the clause number?

**Comment by ronaldtse** [comment]
@anermina sorry for starting this early; let’s put these two documents on hold for now, we need to resolve these gaps with ITU first.

**Comment by anermina** [comment]
@ronaldtse no problem, I'll just switch to #20 .

**Comment by ronaldtse** [comment]
Perfect. Thanks!

**Comment by ronaldtse** [comment]
> Document style for resolution is quite different than for recommendation. As I understood, :doctype: resolution is not completely implemented yet. Please correct me if I'm wrong.
> Should I report all the noticed differences as issues?

Yes please!

> I also have one question regarding the clauses in A.8 recommendation, which also seem to be different than those in the documents I've been working on so far.
> In this recommendation, clauses are untitled, their numbering is in the same row as the rest of the text for that clause, and they shouldn't appear in the table of contents. Should these clauses be defined in .adoc as the rest of them, or they should only be marked-up (boldfaced) to indicate the clause number?

The way to indicate untitled clauses is:

```adoc
=== {blank}

This clause will be shown with a clause number but no clause title.
```

**Comment by anermina** [comment]
These documents are merged. Closing.
