### ISSUE TITLE
Update bundle to work with non-git gems

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#2]
Right now the Gemfile lists out git-gems. We want this repository to work with properly released gems. Task for @opoudjis .

**Comment by CAMOBAP** [comment]
@ronaldtse looks like fixed already because https://github.com/metanorma/mn-itu-docs/blob/master/Gemfile use gems from rubybems.org only

**Comment by ronaldtse** [comment]
Thanks!
