### ISSUE TITLE
Pseudocode title renders as figure title

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#21]
If the pseudocode block has a title, it renders as figure title. (Additionally, the background color changes.)

[pseudocode-title.zip](https://github.com/metanorma/mn-samples-itu/files/3759141/pseudocode-title.zip)

![capture](https://user-images.githubusercontent.com/33627611/67344356-db09b980-f505-11e9-9665-3f93b558aaa3.JPG)

**Comment by opoudjis** [comment]
And indeed, that's because we have to treat pseudocode as *some* sort of asset, and right now we're electing to treat it as figure. But this is inconsistent, true enough: they should be treated consistently with sourcecode, even if they are not labelled as such. So they should not be numbered as figures but just captioned as sourcecode.

I am taking the approach of marking pseudocode up as figures, because that licenses formatting in text; but *rendering* them like sourcecode, in captioning and in styling.

**Comment by opoudjis** [comment]
In ITU HTML, sourcecode has `background-color: #f6f6f6;`, and pseudocode has `background-color: #dddddd;`. That discrepancy is unmotivated, and I will make pseudocode have the same background colour as sourcecode. If pseudocode shouldn't have a background colour in HTML, neither should sourcecode.

**Comment by manuelfuenmayor** [comment]
Hi Nick, I'd recommend to make pseudocode background color same to the example
environment as there are cases where examples include pseudocodes.
Additionally, as suggestion, I think it would be good to make the
background color removable by the user?

**Comment by opoudjis** [comment]
cc'ing @ronaldtse 

Again, we do not allow users the option of customising rendering on something like this, and I don't believe we should. Likewise, we already have different colour for examples and sourcecode throughout the Metanorma stack for HTML output; I don't believe we should make an exception here, although I'm open to example colour taking priority over the colour of any blocks it contains. Ronald, you make the call here.

**Comment by manuelfuenmayor** [comment]
Ok, I understand.

**Comment by ronaldtse** [comment]
> Again, we do not allow users the option of customising rendering on something like this, and I don't believe we should.

Agree.

> I'm open to example colour taking priority over the colour of any blocks it contains. 

What is the motivation for this -- is it because a sourcecode block within an example is an "example"? i.e. all items inside an "example" takes the example background color?

**Comment by opoudjis** [comment]
Motivation is so you don't have patchwork of colours. I would rather the patchwork and logical use of colours, but I am open to being persuaded.

**Comment by ronaldtse** [comment]
@opoudjis logical is good. Special cases not so much, they're hard to manage...

**Comment by manuelfuenmayor** [comment]
For example, this piece of text is a normal example block that includes pseudocode:

![capture2](https://user-images.githubusercontent.com/33627611/67401647-768a4100-f57d-11e9-9bec-457b4b1d8517.JPG)

But, if I use pseudocode environment, I get:

![capture](https://user-images.githubusercontent.com/33627611/67401680-7e49e580-f57d-11e9-97ff-357f4d67f6d7.JPG)

**Comment by opoudjis** [comment]
Could you please paste in the markup for these two?

**Comment by manuelfuenmayor** [comment]
Ok,

First image markup:

````
.Transition rule with if-then and choose:
====
The following transition rule defines the behaviour of agent _ag_ when requesting shared access, i.e., when _ag.mode_ = _shared_. The rule applies the if-then-constructor, the choose-constructor, and an update instruction.

*if* _ag.mode_  stem:[=] _shared_  stem:[^^] _ag.waiting_ *then* +
    *choose* _t_  :  _t_  stem:[in][smallcap]#_Token_# stem:[^^] _t.available_ +
        _t.owner_ stem:[:=] _ag_ +
    *endchoose* +
*endif*
====
````
Second image markup:

````
.Transition rule with if-then and choose:
[pseudocode]
====
The following transition rule defines the behaviour of agent _ag_ when requesting shared access, i.e., when _ag.mode_ = _shared_. The rule applies the if-then-constructor, the choose-constructor, and an update instruction.

*if* _ag.mode_  stem:[=] _shared_  stem:[^^] _ag.waiting_ *then* +
    *choose* _t_  :  _t_  stem:[in][smallcap]#_Token_# stem:[^^] _t.available_ +
        _t.owner_ stem:[:=] _ag_ +
    *endchoose* +
*endif*
====
````

**Comment by opoudjis** [comment]
As I thought. Well, the shading goes by block. If you included the pseudocode inside an example, 

````
====
The following transition rule defines the behaviour of agent _ag_ when requesting shared access, i.e., when _ag.mode_ = _shared_. The rule applies the if-then-constructor, the choose-constructor, and an update instruction.

[pseudocode]
======
pseudocode
======

====

you would have grey and blue alternating.

Myself, I think the grey shading, treating the example as just pseudocode, is correct, though arguably the embedding of pseudocode inside an example is more accurate. I defer to @ronaldtse (within reason).

**Comment by manuelfuenmayor** [comment]
Oh yes, I tested that option too.

````
.Transition rule with if-then and choose:
====
The following transition rule defines the behaviour of agent _ag_ when requesting shared access, i.e., when _ag.mode_ = _shared_. The rule applies the if-then-constructor, the choose-constructor, and an update instruction.

[pseudocode]
====
*if* _ag.mode_  stem:[=] _shared_  stem:[^^] _ag.waiting_ *then* +
    *choose* _t_  :  _t_  stem:[in][smallcap]#_Token_# stem:[^^] _t.available_ +
        _t.owner_ stem:[:=] _ag_ +
    *endchoose* +
*endif*
====
====
`````
But I discarded it when I checked the output:

![capture3](https://user-images.githubusercontent.com/33627611/67405723-257d4b80-f583-11e9-8425-d6e637d36cfd.JPG)

**Comment by opoudjis** [comment]
Your markup won't work: if you embed an example within an example, you need the embedded block to have a different count of delimiters:

````
.Transition rule with if-then and choose:
====
The following transition rule defines the behaviour of agent _ag_ when requesting shared access, i.e., when _ag.mode_ = _shared_. The rule applies the if-then-constructor, the choose-constructor, and an update instruction.

[pseudocode]
=====
*if* _ag.mode_  stem:[=] _shared_  stem:[^^] _ag.waiting_ *then* +
    *choose* _t_  :  _t_  stem:[in][smallcap]#_Token_# stem:[^^] _t.available_ +
        _t.owner_ stem:[:=] _ag_ +
    *endchoose* +
*endif*
=====
====
`````

In your markup, the Asciidoctor parser is closing the example when it sees the second instance of `====`.

**Comment by manuelfuenmayor** [comment]
Ohh I see. Didn't notice that detail. Thanks @opoudjis.

**Comment by ronaldtse** [comment]
@opoudjis We don't have guidance re: HTML formatting. I'd say that the current background of "figures" is too dark for pseudocode (we probably should treat pseudocode like a type of code).

**Comment by opoudjis** [comment]
The current setup in HTML is:

.figure, .Sourcecode: background-colour: #f6f6f6;

.pseudocode: #f6f6f6;

.example: background-color: #e1eef1;

.example .Sourcecode:      background: none;

So:

> I'd say that the current background of "figures" is too dark for pseudocode (we probably should treat pseudocode like a type of code).

Figures, Pseudocode, and Sourcecode all in fact have the same background colour (as of 6 days ago). We ignore the background colour of sourcecode embedded in *examples*; we will do the same for pseudocode. So Pseudocode within examples, like sourcecode within examples, will be shaded blue, not grey.
