### ISSUE TITLE
Pseudocode lines get centered in DOC output

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#22]
[pseudocode-lines-issue.zip](https://github.com/metanorma/mn-samples-itu/files/3759176/pseudocode-lines-issue.zip)

![capture](https://user-images.githubusercontent.com/33627611/67344845-f6c18f80-f506-11e9-95b5-d2f67f91438d.JPG)

**Comment by opoudjis** [comment]
Yes, bug fixed in isodoc.
