### ISSUE TITLE
Strange math rendering

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#24]
This is a strange case.

I need to typeset this piece of text:

![capture1](https://user-images.githubusercontent.com/33627611/67411629-ed2e3b00-f58b-11e9-96fd-e64ecc1e45e7.JPG)

For which I use the following markup:
````
Consider a given vocabulary _V_ containing [smallcap]#_Real_# (but not _currentTime_) and let 
stem:[V^+] be the extension of _V_ with the function symbol _currentTime_. Restrict attention to
stem:[V^+] -states where _currentTime_ evaluates to a real number."
````
And I get this:

![capture2](https://user-images.githubusercontent.com/33627611/67411840-4007f280-f58c-11e9-8955-653e6d3d2517.JPG)

The problem seems to be exclusive for stem:[V^+]. If I remove one of the two "stem:[V^+]" the problem gets solved. If I change the plus sign for a number, it gets solved as well.

[se-issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3763320/se-issue-sample.zip)

**Comment by ronaldtse** [comment]
@manuel489 I think `+...+` means passthrough, you might want to `\+` the first plus sign?

**Comment by manuelfuenmayor** [comment]
@ronaldtse Yes! It works. Thanks.

**Comment by ronaldtse** [comment]
Perfect!
