### ISSUE TITLE
Images left-aligned (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#25]
Images are left-aligned in figure environment (DOC output).

[figure-sample-issue.zip](https://github.com/metanorma/mn-samples-itu/files/3770152/figure-sample-issue.zip)

![capture](https://user-images.githubusercontent.com/33627611/67539134-30cd9580-f6af-11e9-88c1-20bd0e089cff.JPG)

**Comment by opoudjis** [comment]
Impose "figure" style on paragraphs wrapping images in Word; Word stylesheets cannot do the inheritance that HTML CSS can.
