### ISSUE TITLE
Vertical spacing in example block (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#26]
There is no vertical space between paragraphs in example block (doc output). I think, in some cases, it may be necessary for styling purposes.
[example-issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3770168/example-issue-sample.zip)

![capture1](https://user-images.githubusercontent.com/33627611/67540028-f74a5980-f6b1-11e9-918e-72ae8c4f9f04.JPG)

![capture2](https://user-images.githubusercontent.com/33627611/67540031-fa454a00-f6b1-11e9-8088-670dd4b02343.JPG)

**Comment by ronaldtse** [comment]
@manuel489 I agree, and in fact, this also applies to ISO Word output. The text contained within an EXAMPLE is not indented causing readers to wonder whether the text following the EXAMPLE belongs to the EXAMPLE or a separate paragraph.

**Comment by opoudjis** [comment]
Quite right. The Word stylesheets are not differentiating div.example from p.example with regard to spacing before/after.
