### ISSUE TITLE
couldn't install the ruby-xslt gem in this bundle

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn-samples-itu#3]
From @ronaldtse 

> """
ITU says they couldn't install the ruby-xslt gem in this bundle: https://github.com/metanorma/mn-itu-docs
> But they can install Metanorma Chocolatey fine.
> (they had to add the "C:\tools\ruby25\bin" path to "environment variables" to make Ruby work)
"""

AFAIK action items are:
 - Add Appveyor CI
 - ~Update Gemfile.lock~ will be done in the scope of https://github.com/metanorma/mn-itu-docs/issues/2

**Comment by ronaldtse** [comment]
@CAMOBAP795 We're pending on this, right?
