### ISSUE TITLE
Lines get justified-aligned when a line-break is added in table environment (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#31]
Please, refer to the sample:

[table-issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3786427/table-issue-sample.zip)

![capture7](https://user-images.githubusercontent.com/33627611/67820379-65669600-fa8f-11e9-9df2-b082900b84ea.JPG)

**Comment by opoudjis** [comment]
Text in tables is indeed either left or center aligned in the samples, never justified.

**Comment by opoudjis** [comment]
Alignment is in fact being processed in Metanorma; but Word does not propagate table cell alignment into the paragraphs underneath it. (Recall that Word CSS is poorly implemented.) Will propagate in isodoc.

**Comment by manuelfuenmayor** [comment]
@opoudjis, the issue raises when the style option is applied to the cell, i.e. by prefixing the cell with `a` (`a|`)
Here's a modified version of the sample where all the lines of the second column get justified.
````
|===
<.<| _X_ <.<a| 0-ary function + 
application
<.<| _f(t~1~ ,..., t~n~)_ <.<a| Function application with + 
n argument expressions
<.<| *if* _Formula_ *then* _Term_ *else* _Term_ *endif* <.<a| Conditional expression; + 
again we use *elseif* instead of *else* *if*
<.<| *s-* _ (_) <.<a| Tuple selection function + 
(see Tuples below)
<.<| *mk-* _ (...) <.<a| Tuple construction + 
(see Tuples below)
<.<| *inv-* _ (...) <.<a| The inverse of a function or map, +
**inv**-_Fun(x)_ stem:[=_{"def"}] _take_({ _a_ stem:[in] _D_ : _Fun(a)_ stem:[=] _x_ })
|===
````

**Comment by opoudjis** [comment]
The issue is arising because, when there is asciidoc styling, the renderer inserts a paragraph in the HTML source, but in Word that paragraph is ignoring any alignment on its table cell parent. Am fixing now.
