### ISSUE TITLE
Crossreferences font size are smaller than normal text (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#32]
Please, refer to the sample:
[crossreference-issue-sample.zip](https://github.com/metanorma/mn-samples-itu/files/3786463/crossreference-issue-sample.zip)

![capture8](https://user-images.githubusercontent.com/33627611/67820852-47019a00-fa91-11e9-8471-911d72917a05.JPG)

**Comment by opoudjis** [comment]
URL styling is being applied to cross references. It should only be applied to actual urls, as opposed to any hyperlinked text. The original does not have this problem, because it is not hyperlinking cross-references...

... actually, simplest thing is simply not to hyperlink crossreferences.
