### ISSUE TITLE
Wrong page numbering in table of contents (DOC output)

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-itu#35]
Page numbering renders as 1 in all sections

![capture-toc](https://user-images.githubusercontent.com/33627611/68072665-7698f680-fd5e-11e9-88f1-576cf98ce9ca.JPG)

I think this bug has influence in all the flavours.

**Comment by opoudjis** [comment]
Known issue: the right numbering happens when you refresh the ToC (right-click, select update). To make this happen automatically on opening the document, we would have to inject a VB script to do so every time we open a Word Document, and that would have lots of bad consequences.

**Comment by ronaldtse** [comment]
I think we ought to mention this in the online documentation. Where can we put this?

**Comment by opoudjis** [comment]
https://www.metanorma.com/author/topics/building/output-formats/

**Comment by opoudjis** [comment]
Done
