### ISSUE TITLE
Utilize user-specified reference tags citation syntax

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#59]
Utilize new citation syntax implemented in https://github.com/metanorma/metanorma-standoc/issues/159 .

Many ITU references go with "[b-ITU xxx]", and this repo's documents will need this.

Ping @manuel489 thanks!

**Comment by manuelfuenmayor** [comment]
Added in https://github.com/metanorma/mn-samples-itu/pull/65

**Comment by manuelfuenmayor** [comment]
@ronaldtse , is there something else remaining to do in this issue?

**Comment by ronaldtse** [comment]
All good. Thanks!
