### ISSUE TITLE
Convert ITU provided documents under `reference-docs/`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#6]
ITU has given three documents to exercise the compiler, I put them under `reference-docs/`. 

The purposes are:

* Y.3507: contains figures inside a table
* G.650.1: contains a number of equations, and
* Z.100 Annex F1: uses different types of fonts.

@opoudjis could you please help convert them? Thanks!

**Comment by ronaldtse** [comment]
@hofmannedv , @opoudjis will let you know which document to handle here. He has done a preliminary conversion of the documents, and will make the drafts available here.

**Comment by opoudjis** [comment]
I have indeed done that, and have emailed @hofmannedv and @zoras instructions for their respective documents.

The different fonts... are not implemented in Metanorma; what is implemented is smallcap and bold/italic/smallcap combinations, which are abundant in the document. And I hope that's what they intended for Z.100 Annex F1.

**Comment by opoudjis** [comment]
Task assignment is: 

* Y.3507: @tgolubev 
* G.650.1: @zoras and @anermina
* Z.100 Annex F1: @hofmannedv and @manuel489

**Comment by ronaldtse** [comment]
Pinging all @editors : its been a week and a half since the assignments and we need the documents completed within 48 hours. Let me or @opoudjis know if you run into any problems.

**Comment by ronaldtse** [comment]
These are done, closing.
