### ISSUE TITLE
ITU G.650: Cross-reference to the note in subsubclause

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-itu#74]
Cross-reference to the note (in the images below) indicates the number of subclause, instead of the subsubclause where note is positioned. This doesn't happen in the attached test document using similar cross-referencing.

Original:
![image](https://user-images.githubusercontent.com/55683568/80261172-f5297d80-8689-11ea-9215-2c2459c6344c.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80261194-02466c80-868a-11ea-9c50-94fbb25e01be.png)

[test_notes_referencing.zip](https://github.com/metanorma/mn-samples-itu/files/4531997/test_notes_referencing.zip)

**Comment by opoudjis** [comment]
Yes. Terms are not being tracked as containers for notes in crossreferences, so this is grabbing the nearest clause instead. Wow. An error of very long standing.
