### ISSUE TITLE
ITU H.782: Differences between the original and generated DOC

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-itu#79]
Following differences were noticed:

- "W3C" is duplicated in generated DOC, although there is no duplication in .adoc:
`* [[[xmlschema, W3C XMLSchema]]] W3C Recommendation (2004), _XML Schema Part 2: Datatypes Second Edition_.`
`* [[[csstransforms,(b-W3C CSS Transforms)W3C CSS Transforms]]] W3C, _CSS_ _Transforms Module Level 1_. https://www.w3.org/TR/css-transforms-1/[https://www.w3.org/TR/css-transforms-1/] – [Last accessed 02 Oct. 2018].`

Moreover, when auto-fetching isn't possible, document identifier is rendered twice - between the brackets and in the short reference description.

Original:
![image](https://user-images.githubusercontent.com/55683568/80615497-0b478d00-8a40-11ea-8fa6-76b3b0aadbd6.png)
![image](https://user-images.githubusercontent.com/55683568/80618253-6464f000-8a43-11ea-9575-8c6fae20f7f3.png)

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80615571-23b7a780-8a40-11ea-98de-5f6c9401697e.png)
![image](https://user-images.githubusercontent.com/55683568/80618310-79418380-8a43-11ea-8c6a-a3c721e2f605.png)

- Some of the b-references and cross-references are rendered differently than in the original document. They include more brackets in generated DOC.

Original:
![image](https://user-images.githubusercontent.com/55683568/80616296-0afbc180-8a41-11ea-984f-26bb5a9111f5.png)

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80616342-16e78380-8a41-11ea-93d5-fbc19573872a.png)

- In the original document, reference tag/ID and its corresponding description are written like in two separate columns (similar to definitions in Metanorma). In other words, spacing between the tag/ID and its short description differs.

Original:
![image](https://user-images.githubusercontent.com/55683568/80396212-9dbb2580-88b4-11ea-9144-a74aace4852b.png)

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80621810-21f1e200-8a48-11ea-8655-b683e5b7a10e.png)

**Comment by anermina** [comment]
Update: Following issue also appears in A.1500 (T-Editing Guidelines) document, so it might be some more general issue, rather document-specific.

> * Some of the b-references and cross-references are rendered differently than in the original document. They include more brackets in generated DOC.

Example from ITU A.1500:
![image](https://user-images.githubusercontent.com/55683568/81444513-8e22c300-9177-11ea-9f28-3b766f0e3081.png)

**Comment by opoudjis** [comment]
> "W3C" is duplicated in generated DOC, although there is no duplication in .adoc: 

W3C references are now being fetched automatically. By default the SDO abbreviation is prefixed to the document number; in the autofetched references, W3C is already there, so W3C will no longer be auto-prefixed.

**Comment by opoudjis** [comment]
> Moreover, when auto-fetching isn't possible, document identifier is rendered twice - between the brackets and in the short reference description.

ITU reference format is consistently: _[identifier]  Publisher (if recognised) Identifier, Title._ The identifier is "W3C XMLSchema". It may look similar to the title, but consistency is more important.

**Comment by opoudjis** [comment]
Prevent double brackets in rendering.

**Comment by opoudjis** [comment]
Forcing bibliography alignment by table.

**Comment by opoudjis** [comment]
@anermina @manuel489 This is a significant change in how I'm processing bibliographies; please check all ITU documents.

**Comment by manuelfuenmayor** [comment]
> @anermina @manuel489 This is a significant change in how I'm processing bibliographies; please check all ITU documents.

Ok @opoudjis , ticket created in https://github.com/metanorma/mn-samples-itu/issues/105
