### ISSUE TITLE
Investigate compilation warnings for G.650

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-samples-itu#8]
In response to @anermina: need to investigate warnings about crossreferences:

````
IDREF "a<em>6_4_1Reference_test_method" without matching ID @ 1844:349
IDREF "a<em>6_3_1_3_3Calculations" without matching ID @ 1454:241
IDREF "a<em>I_1Limited_negative_error_method" without matching ID @ 2366:316
IDREF "a<em>6_3_1_3_2Transmission_through_the_reference_sample" without matching ID @ 1338:95
IDREF "a</em>6_4_2First_alternative_test_method" without matching ID @ 1844:437
IDREF "a</em>I_2Least_squares_method" without matching ID @ 2366:373
IDREF "a</em>6_3_1_2_3Launching_conditions" without matching ID @ 1338:677
IDREF "a</em>6_3_1_3_4Determination_of_cut-off_wavelength" without matching ID @ 1454:319
No label has been processed for ID fig1
No label has been processed for ID [fig1]
No label has been processed for ID fig2
No label has been processed for ID [fig2]
No label has been processed for ID fig2
```` 

These may or may not be mark up issues. It may be that anchors must not contain underscores (which is a problem, given that reverse_adoc is generating these.)

There is also a profusion of bibitem/relation and other errors in the grammar parse, which need to be looked at.

**Comment by opoudjis** [comment]
The former issues with `<em>` embedded in anchors are because `__` inside of anchors is being treated by Asciidoctor as a word-internal italics marker. That should just be eliminated in any Word to Asciidoctor conversion https://github.com/metanorma/reverse_adoc/issues/29. Will ask editors to remove from their documents.

**Comment by opoudjis** [comment]
With images restored, and anchors addressed, those warnings have disappeared. I am addressing here syntax errors:

* biblio.rnc does not allow paragraphs or definition lists in bibdata/abstract, only formatted strings. I may update biblio.rnc to include paragraphs etc, but I'm not convinced I should. Issue I will leave open: https://github.com/metanorma/metanorma-standoc/issues/138
* I'm allowing arbitrary strings as series types; ITU introduces secondary and tertiary series, whereas Relaton to date only defines primary and alt.
* Making ITU editorialgroup/group optional in grammar
* Added bibdata/ext/ip-notice-received to grammar
* Allow arbitrary clauses in preface
* Allow clauses to contain terms, definitions
* Captions of blocks need to include not just text but formatting
* Allow boilerplate for terms definitions references
* There is an erroneous relation type in ITU references: https://github.com/relaton/relaton-itu/issues/25

**Comment by opoudjis** [comment]
There are other errors, but they are to do with markup, and I cannot work on this further now.

**Comment by opoudjis** [comment]
Massive increase in error reporting with the update to asciimath, validation is complaining about attributes in MathML namespace. Need to ensure attributes are ignored in extraneous namespaces, as part of xs:any.

**Comment by opoudjis** [comment]
Allow content sections (preface) to have hanging paragraphs.

**Comment by opoudjis** [comment]
All 10 remaining issues are hanging paragraphs, and orphan terms. These should be reported as issues for good practice.

**Comment by ronaldtse** [comment]
@opoudjis can we have actual warnings that says "hanging paragraphs" and "orphan terms"?

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-standoc/issues/193, https://github.com/metanorma/metanorma-standoc/issues/194
