### ISSUE TITLE
ITU J.1108 - reference document for checking .adoc

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-itu#81]
Since we have a draft version for ITU J.1108 as a referent document, and the final version was published in the meanwhile, I would like to check how the .adoc should be modified.
Currently, it includes many "Draft [New]" tags. 

Should I correct .adoc in accordance to https://www.itu.int/rec/T-REC-J.1108/en, or to the draft version from https://github.com/metanorma/mn-samples-itu/tree/master/references/itu-t?

**Comment by ronaldtse** [comment]
@anermina can we keep both versions so we have a draft and also a published copy? Thanks!

**Comment by anermina** [comment]
Thanks @ronaldtse . Sure, both versions are now added via https://github.com/metanorma/mn-samples-itu/pull/130. Closing.
