### ISSUE TITLE
ITU Y.3507: Differences between the original and generated DOC

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-itu#85]
- Figures are numbered differently (they have chapter/section indication in the original document). Since this wasn't noticed in other ITU recommendations, this issue is opened just to double-check whether this is an inconsistency in the original ITU recommendations, which we can ignore (?). For example, original ITU P.1203 uses the same numbering style as generated DOC.

Generated:
![image](https://user-images.githubusercontent.com/55683568/80693088-cde00f80-8ad2-11ea-9c38-8423e182107f.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/80690110-a38c5300-8ace-11ea-88b6-3f1e14ccbcc1.png)

**Comment by opoudjis** [comment]
Suggest escalating to Ronald, but inconsistencies are likely.

**Comment by anermina** [comment]
I updated document attributes in order to use hierarchical numbering, which could enable having the same output as in the original document, without impacting other ITU documents. However, document attribute `:hierarchical-object-numbering:` seems not to be working, so I opened a new ticket (https://github.com/metanorma/metanorma-itu/issues/217). Closing this one.
