### ISSUE TITLE
ITU Z.100: (Un-)numbering pseudocode blocks

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-itu#86]
In ITU Z.100, pseudocode is written between `====` delimiters marked with `[%unnumbered]` attribute, but it is still numbered as figure. Is there an option to avoid having a title? Delimiter `----` wouldn't be good in this case because of the text formatting.

Original:
![image](https://user-images.githubusercontent.com/55683568/80766926-e0942c00-8b46-11ea-9dea-e5c89f8058b8.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80766894-c9553e80-8b46-11ea-8dd7-c87b342db0b0.png)

**Comment by opoudjis** [comment]
So are you saying `[%unnumbered]` on pseudocode results in a "Figure" caption, or a "Figure F1-45" caption?

Either is an error: if no title is provided, and the figure is unnumbered, there should be nothing there. Treating as a bug.

**Comment by anermina** [comment]
It is resulting in "Figure x.y" caption (treated as numbered figure).

**Comment by anermina** [comment]
Update: I changed [pseudocode] to [.pseudocode], as per https://github.com/metanorma/metanorma-standoc/issues/275#issuecomment-627402563. Generated results are the same.

**Comment by opoudjis** [comment]
Pseudocode has been ignoring the unnumbered attribute; fixing.
