### ISSUE TITLE
URGENT: Unable to build documents.html

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#94]
In mn-samples-itu, the Relaton index is not showing any document, but all are built. Reproduced locally as well. Seems like a Relaton-ITU problem?

<img width="619" alt="Screen Shot 2020-05-10 at 12 48 59 PM" src="https://user-images.githubusercontent.com/11865/81491107-a18b7680-92bc-11ea-90f9-544045e9eb3b.png">

**Comment by andrew2net** [comment]
fixed https://github.com/relaton/relaton-itu/issues/38#issuecomment-626373444
