### ISSUE TITLE
Convert ITU G.191 STL manual (from LaTeX)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#96]
G.191's source can be found here:

* https://github.com/openitu/STL/tree/dev/doc/manual
* https://github.com/simaocampos/STL-manual

The first link is supposed to be updated to 2019, the second is 2018.

If the first link works, we can ignore the second.

**Comment by ronaldtse** [comment]
Ping @manuel489 @anermina when you have time. Thanks!

**Comment by anermina** [comment]
I can take this task, but I think it's not named properly. Document which is available from the given link is "ITU-T Software Tool Library, release 2019" (STL manual), while we already have ITU G.191 converted here: https://github.com/metanorma/mn-samples-itu/blob/master/sources/G.191.adoc.

@ronaldtse , could you please confirm STL manual needs to be converted, so I can proceed?

**Comment by ronaldtse** [comment]
@anermina you're right, I've just fixed the title.

According to G.191, it says "Recommendation ITU-T G.191 includes an electronic attachment containing STL2019 and manual."

So we want to convert the manual here. Thanks!

**Comment by anermina** [comment]
Pending due to rendering issues: https://github.com/metanorma/metanorma-iso/issues/395.

**Comment by anermina** [comment]
Converted in #116 .
